# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AutoCrawl

on:
  schedule:
    - cron: '0 8,20 * * *'
  push:
    branches: [main]

jobs:
  crawl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9
    - name: Install dependencies
      run: |
        bash install_env.sh
    - name: Auto crawl
      run: |
        ./env/bin/python3 -m crawlers
    - name: Commit and push
      run: |
        git config user.email "ww-rm@qq.com"
        git config user.name "ww-rm"
        git add .
        git commit -m "autorun crawler"
        git push
