# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: POA

on:
  push:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        bash install_env.sh
    # - name: Test crawler
    #   run: |
    #     ./env/bin/python3 -m crawlers
    # - name: Test hotspot
    #   run: |
    #     ./env/bin/python3 -m hotspot
    # - name: Test knowledge graph
    #   run: |
    #     ./env/bin/python3 -m kgraph 
    # - name: Test gendb
    #   run: |
    #     ./env/bin/python3 -m gendb.py
